<?php
// PHP permanent URL redirect - generated by www.rapidtables.com
// header("Location: https://cgroupassets.com/", true, 301);


// exit();
?>

<h1>Cosmetics Group Assets For Fashion Coming Soon</h1>